### ISSUE TITLE
function callback?

### ISSUE THREAD

**Issue by tokiodeo** [kamaliev/google-maps-angular2#2]
A return function can be integrated callback

**Comment by maikeruit** [comment]
@ZWTOKIO Hello! What do you mean?

**Comment by tokiodeo** [comment]
I do not know how to speak English, sorry.
Spanish question:
mi pregunta es si puedo integrarle una función que procese datos por detrás al usar el ' drag ' del mapa gracias.

**Comment by maikeruit** [comment]
@ZWTOKIO 
`map.addListener('drag', function() {
//you code
  });`

For more information, please visit: https://developers.google.com/maps/documentation/javascript/events?hl=en
